[package]
name = "stm32lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.stm32f4xx-hal]
features = ["stm32f401", "rt"]
version = "0.13"